### ISSUE TITLE
Please add vendor: Malware Patrol

### ISSUE THREAD

**Issue by AndreC10002** [curated-intel/Ukraine-Cyber-Operations#26]
Hello,
Would you please add our offer to the list of vendors supporting Ukraine?  And, it'd be great to sort the list alphabetically. :-)

Here is our information:

Malware Patrol
- Source of information: https://www.linkedin.com/feed/update/urn:li:activity:6903059206522712064/
- Services being offered: Free 6 months DNS Firewall service subscription
- Who is eligible: Ukraine-based companies and government entities
- How are the services accessed: Complete the DNS Firewall evaluation form and put "Ukraine based" in the comments. Then, follow the instructions to set up an evaluation call with Malware Patrol to discuss the set-up for your security environment. https://www.malwarepatrol.net/dns-firewall-evaluation-request/?source=ukraine

Please let me know if you have any questions or need additional information.

Thank you.

**Comment by BushidoUK** [comment]
Nice one MalwarePatrol & Thanks to mihaid-b for adding
