### ISSUE TITLE
Wrong IoC types in feeds

### ISSUE THREAD

**Issue by sustefil** [curated-intel/Ukraine-Cyber-Operations#32]
Hi,

I have found IP IoCs being flagged as domains.

For example in this feed:

https://github.com/curated-intel/Ukraine-Cyber-Operations/blob/main/KPMG-Egyde_Ukraine-Crisis_Feeds/MISP-CSV_MediumConfidence_Filtered/Ukraine-Crisis_RecordedFuture_ThreatHunt_Feed.csv

**Comment by BushidoUK** [comment]
Thanks for flagging!
cc @DISREL

**Comment by DISREL** [comment]
Hey! Thanks for the flag.

Will fix and update them ASAP.
